/**
 * The composition sweep: proof that the layered character system is
 * total.
 *
 * ## The strategy, and why it is not exhaustive
 *
 * Fourteen dimensions — ten appearance categories, the worn outfit, the
 * held weapon, the installed cyberware set, and the dye in the coat —
 * cross-multiply to tens of billions of descriptors, before a single
 * facing or animation frame is drawn. That product is not a test.
 *
 * What runs instead is the pair of strategies documented in
 * ./combinations, both generated by a seeded, pure builder so a failing
 * combination reproduces exactly:
 *
 * 1. **Every option against the stock look.** One case per catalog
 *    entry, per outfit, per weapon, per implant, per tin, everything
 *    else held at the default. Art that is simply wrong — bad width,
 *    off-palette character, pixels outside its region — fails here.
 * 2. **All-pairs coverage.** Every value pair of every dimension pair
 *    appears together in at least one case. Interaction bugs are
 *    overwhelmingly two-way (this hat over that hair, that rifle on
 *    this build), and all-pairs catches every one of them in a few
 *    hundred cases.
 *
 * Cases whose composed descriptors serialize identically are pruned:
 * the interaction rules genuinely collapse them (a hood hides hair, so
 * nine hair styles under one are a single picture), and a separate test
 * below proves the collapse honest rather than assumed.
 *
 * ## What is swept where
 *
 * South and west are exact mirrors of east and north (see
 * bodyViewForFacing), so the authored facings carry the frame sweep and
 * the mirror is checked as its own invariant rather than doubling every
 * loop. Reaction frames — four kinds, both recoil directions — run over
 * the per-option cases, because a reaction transform is applied to the
 * finished composite and cannot depend on which *combination* produced
 * it, only on which layers are present.
 *
 * Nothing here asserts inside a loop: every check appends a repro line
 * naming the exact combination and pose, and the test asserts once
 * against the report (see ./report).
 */
import { describe, expect, it } from "vitest";
import {
  attackClassFor,
  composedCharacterGrid,
  composedCharacterKey,
  composedFrameKey,
  layerArtGrid,
  layerOrderFor,
  type ComposedCharacter,
  type LayerSlot,
} from "../../iso/art/layers";
import { composeCharacter } from "../appearance";
import {
  BODY_BUILD_IDS,
  BODY_FRAME,
  BODY_VIEW_IDS,
  bodyViewForFacing,
} from "../../iso/art/layers/body";
import { attackFrameCount } from "../../iso/attack";
import { REACTION_KINDS, reactionFrameCount } from "../../iso/reaction";
import type { Facing, MotionState } from "../../iso/animation";
import { entityFrame, characterArt } from "../../iso/art/entity";
import {
  gridErrors,
  mirrored,
  silhouetteArea,
  silhouetteGrid,
  type PixelGrid,
} from "../../iso/art/pixel";
import { HAIR_WALK_REGION, hairWalkGrid } from "../../iso/art/layers/hair";
import { describeCase, describeFrame, sweepPlan } from "./cases";
import { describeFault, layerFaults, pixelsOutside } from "./regions";
import { faultReport } from "./report";

const FACINGS: readonly Facing[] = ["n", "e", "s", "w"];
/** The authored views; south and west mirror these. */
const AUTHORED: readonly Facing[] = ["e", "n"];
const AWAY: readonly (-1 | 1)[] = [-1, 1];

const plan = sweepPlan();
const perOption = plan.perOption;

/** Every loop/attack frame index of a case, as (state, frame) pairs. */
function posesFor(character: ComposedCharacter): [MotionState, number][] {
  const poses: [MotionState, number][] = [];
  for (let f = 0; f < 4; f++) poses.push(["idle", f]);
  for (let f = 0; f < 6; f++) poses.push(["walk", f]);
  const attack = attackFrameCount(attackClassFor(character));
  for (let f = 0; f < attack; f++) poses.push(["attack", f]);
  return poses;
}

/**
 * Everything one composed frame must satisfy: valid palette-indexed
 * art, the exact frame dimensions, and a silhouette to trace. Returns
 * the fault lines, empty when the frame is sound.
 */
function frameFaults(grid: PixelGrid, where: string): string[] {
  const faults: string[] = [];
  for (const error of gridErrors(grid)) faults.push(`${where}: ${error}`);
  if (grid.length !== BODY_FRAME.height) {
    faults.push(`${where}: ${grid.length} rows, expected ${BODY_FRAME.height}`);
  }
  const width = grid[0]?.length ?? 0;
  if (width !== BODY_FRAME.width) {
    faults.push(`${where}: ${width} columns, expected ${BODY_FRAME.width}`);
  }
  const silhouette = silhouetteGrid(grid);
  if (silhouetteArea(grid) === 0) {
    faults.push(`${where}: silhouette is empty — nothing to trace or flash`);
  }
  if (
    silhouette.length !== grid.length ||
    (silhouette[0]?.length ?? 0) !== width
  ) {
    faults.push(`${where}: silhouette does not match the frame`);
  }
  return faults;
}

describe("the sweep plan", () => {
  it("stands in for a cross product nobody could run", () => {
    expect(plan.exhaustive).toBeGreaterThan(1e9);
    expect(plan.cases.length).toBeLessThan(600);
    // Both halves of the strategy are present: the per-option baseline
    // leads, all-pairs follows.
    expect(plan.generated.length).toBeGreaterThan(perOption.length);
  });

  it("reaches every value of every dimension", () => {
    const faults: string[] = [];
    plan.dimensions.forEach((dimension, d) => {
      for (let v = 0; v < dimension.values.length; v++) {
        if (!plan.generated.some((row) => row[d] === v)) {
          faults.push(`dimension "${dimension.name}" never used value ${v}`);
        }
      }
    });
    expect(faultReport(faults)).toBe("");
  });

  it("is deterministic: the same seed rebuilds the same cases", () => {
    const again = sweepPlan();
    expect(again.cases.map((one) => one.key)).toEqual(
      plan.cases.map((one) => one.key),
    );
  });

  it("prunes only cases that really are the same picture", () => {
    // The interaction rules collapse looks (a hood hides hair, a
    // rebreather covers the eyes). Prove the collapse rather than trust
    // it: descriptors that serialized the same must compose the same.
    const faults: string[] = [];
    for (const group of plan.collisions) {
      const [first, ...rest] = group.cases;
      if (!first) continue;
      for (const other of rest) {
        for (const facing of AUTHORED) {
          const a = composedCharacterGrid(first.character, facing, "idle", 0);
          const b = composedCharacterGrid(other.character, facing, "idle", 0);
          if (a.join("\n") !== b.join("\n")) {
            faults.push(
              `descriptor collision draws two pictures (${facing}):\n  ${describeCase(first)}\n  ${describeCase(other)}`,
            );
          }
        }
      }
    }
    expect(faultReport(faults)).toBe("");
  });
});

describe("every resolved layer honors its region", () => {
  it("draws inside its declared box, and casts no shadow but the body's", () => {
    const faults: string[] = [];
    for (const sweepCase of plan.cases) {
      for (const view of BODY_VIEW_IDS) {
        for (const layer of sweepCase.character.layers) {
          const grid = layerArtGrid(layer.slot, layer.art, view);
          if (!grid) continue;
          for (const fault of layerFaults(layer.slot, layer.art, view, grid)) {
            faults.push(`${describeFault(fault)} — ${describeCase(sweepCase)}`);
          }
        }
      }
    }
    expect(faultReport(faults)).toBe("");
  });

  it("keeps the walk trail inside the region the shift is allowed", () => {
    const faults: string[] = [];
    for (const sweepCase of plan.cases) {
      for (const layer of sweepCase.character.layers) {
        if (layer.slot !== "hair") continue;
        for (const view of BODY_VIEW_IDS) {
          const grid = layerArtGrid("hair", layer.art, view);
          if (!grid) continue;
          const outside = pixelsOutside(
            hairWalkGrid(layer.art, grid),
            HAIR_WALK_REGION,
          );
          if (outside.length > 0) {
            faults.push(
              `hair:${layer.art}[${view}] walk trail leaves its region: ${outside.slice(0, 6).join(", ")} — ${describeCase(sweepCase)}`,
            );
          }
        }
      }
    }
    expect(faultReport(faults)).toBe("");
  });

  it("keeps the slot draw order for every facing", () => {
    const faults: string[] = [];
    for (const sweepCase of plan.cases) {
      for (const facing of FACINGS) {
        const order = layerOrderFor(facing);
        const ranks = [...sweepCase.character.layers]
          .sort(
            (a, b) => order.indexOf(a.slot) - order.indexOf(b.slot),
          )
          .map((layer) => order.indexOf(layer.slot));
        const sorted = ranks.every(
          (rank, i) => i === 0 || rank >= (ranks[i - 1] ?? rank),
        );
        if (!sorted) {
          faults.push(`[${facing}] out of z-order — ${describeCase(sweepCase)}`);
        }
        const held: LayerSlot = "weapon";
        const behind = order.indexOf(held) === 0;
        if (behind !== (facing === "n" || facing === "w")) {
          faults.push(`[${facing}] weapon draws on the wrong side of the body`);
        }
      }
    }
    expect(faultReport(faults)).toBe("");
  });
});

describe("every combination composes", () => {
  it("renders valid frames for every loop and attack pose, both authored views", () => {
    const faults: string[] = [];
    for (const sweepCase of plan.cases) {
      for (const facing of AUTHORED) {
        for (const [state, frame] of posesFor(sweepCase.character)) {
          let grid: PixelGrid;
          try {
            grid = composedCharacterGrid(sweepCase.character, facing, state, frame);
          } catch (error) {
            faults.push(
              `${describeFrame(sweepCase, facing, state, frame)}: threw ${String(error)}`,
            );
            continue;
          }
          faults.push(
            ...frameFaults(grid, describeFrame(sweepCase, facing, state, frame)),
          );
        }
      }
    }
    expect(faultReport(faults)).toBe("");
  });

  it("mirrors south and west from the authored views, pixel for pixel", () => {
    const faults: string[] = [];
    const pairs: [Facing, Facing][] = [
      ["e", "s"],
      ["n", "w"],
    ];
    for (const sweepCase of plan.cases) {
      for (const [authored, mirroredFacing] of pairs) {
        for (const [state, frame] of [
          ["idle", 0],
          ["walk", 3],
        ] as [MotionState, number][]) {
          const source = composedCharacterGrid(
            sweepCase.character,
            authored,
            state,
            frame,
          );
          const flipped = composedCharacterGrid(
            sweepCase.character,
            mirroredFacing,
            state,
            frame,
          );
          if (mirrored(source).join("\n") !== flipped.join("\n")) {
            faults.push(
              `${describeFrame(sweepCase, mirroredFacing, state, frame)}: not the mirror of ${authored}`,
            );
          }
        }
      }
    }
    expect(faultReport(faults)).toBe("");
  });

  it("renders every reaction frame, both recoil directions", () => {
    const faults: string[] = [];
    for (const sweepCase of perOption) {
      for (const facing of AUTHORED) {
        for (const kind of REACTION_KINDS) {
          for (let frame = 0; frame < reactionFrameCount(kind); frame++) {
            for (const awayX of AWAY) {
              const where = describeFrame(
                sweepCase,
                facing,
                "react",
                frame,
                `${kind}${awayX > 0 ? "+" : "-"}`,
              );
              let grid: PixelGrid;
              try {
                grid = composedCharacterGrid(
                  sweepCase.character,
                  facing,
                  "react",
                  frame,
                  { kind, awayX },
                );
              } catch (error) {
                faults.push(`${where}: threw ${String(error)}`);
                continue;
              }
              faults.push(...frameFaults(grid, where));
            }
          }
        }
      }
    }
    expect(faultReport(faults)).toBe("");
  });

  it("needs a variant for a reaction frame rather than guessing one", () => {
    const [first] = plan.cases;
    expect(first).toBeDefined();
    expect(() =>
      composedCharacterGrid(first!.character, "e", "react", 0),
    ).toThrow(/reaction variant/);
  });
});

describe("fixed points across every composition", () => {
  it("holds the frame size and anchor for every case", () => {
    const faults: string[] = [];
    for (const sweepCase of plan.cases) {
      const frame = entityFrame(characterArt(sweepCase.character));
      if (
        frame.width !== BODY_FRAME.width ||
        frame.height !== BODY_FRAME.height ||
        frame.anchorX !== BODY_FRAME.anchorX ||
        frame.anchorY !== BODY_FRAME.anchorY
      ) {
        faults.push(`frame drifted — ${describeCase(sweepCase)}`);
      }
      if (!BODY_BUILD_IDS.includes(sweepCase.character.build)) {
        faults.push(`unknown build — ${describeCase(sweepCase)}`);
      }
    }
    expect(faultReport(faults)).toBe("");
  });

  it("gives every case and pose its own bake key, and never reuses one", () => {
    const seen = new Map<string, string>();
    const faults: string[] = [];
    for (const sweepCase of plan.cases) {
      for (const facing of FACINGS) {
        for (const [state, frame] of posesFor(sweepCase.character)) {
          const key = composedFrameKey(sweepCase.character, facing, state, frame);
          const previous = seen.get(key);
          const where = describeFrame(sweepCase, facing, state, frame);
          if (previous !== undefined && previous !== where) {
            faults.push(`bake key collision:\n  ${where}\n  ${previous}`);
          }
          seen.set(key, where);
        }
      }
    }
    expect(faultReport(faults)).toBe("");
  });

  it("keys the same descriptor identically however it was built", () => {
    const faults: string[] = [];
    for (const sweepCase of plan.cases) {
      // Rebuilt from the recorded appearance and equipment — a
      // different object graph reaching the same picture must reach the
      // same cache key, or the bake cache would miss on every frame.
      const rebuilt = composeCharacter(sweepCase.appearance, {
        ...sweepCase.equipment,
        enhancements: { ...sweepCase.equipment.enhancements },
      });
      if (composedCharacterKey(rebuilt) !== sweepCase.key) {
        faults.push(`key is not stable — ${describeCase(sweepCase)}`);
      }
    }
    expect(faultReport(faults)).toBe("");
  });
});

describe("the sweep would notice", () => {
  it("catches a layer whose art escaped its region", () => {
    const rogue = Array.from({ length: BODY_FRAME.height }, (_, y) =>
      y === BODY_FRAME.height - 1 ? "K".padEnd(BODY_FRAME.width, ".") : ".".repeat(BODY_FRAME.width),
    );
    const faults = layerFaults("hair", "buzz", "front", rogue);
    expect(faults).toHaveLength(1);
    expect(describeFault(faults[0]!)).toContain("outside its hair region");
  });

  it("catches a layer that started casting a shadow", () => {
    const shady = Array.from({ length: BODY_FRAME.height }, (_, y) =>
      y === 5 ? ".".repeat(12) + "z" + ".".repeat(BODY_FRAME.width - 13) : ".".repeat(BODY_FRAME.width),
    );
    const faults = layerFaults("headwear", "cap", "front", shady);
    expect(describeFault(faults[0]!)).toContain("ground shadow");
  });

  it("catches an off-palette pixel in a composed frame", () => {
    // "@" is deliberately not a palette entry, and stays that way: the
    // v3 half-steps took most of the punctuation (see ../../iso/art/palette).
    const broken = Array.from({ length: BODY_FRAME.height }, () =>
      "@".repeat(BODY_FRAME.width),
    );
    expect(frameFaults(broken, "fixture").join("\n")).toContain("not in the palette");
  });

  it("catches a frame with nothing to trace", () => {
    const empty = Array.from({ length: BODY_FRAME.height }, () =>
      ".".repeat(BODY_FRAME.width),
    );
    expect(frameFaults(empty, "fixture").join("\n")).toContain("silhouette is empty");
  });

  it("maps every facing onto an authored view", () => {
    for (const facing of FACINGS) {
      const { view } = bodyViewForFacing(facing);
      expect(BODY_VIEW_IDS).toContain(view);
    }
  });
});
