/**
 * Turn-based combat engine: initiative, actions, seeded-RNG damage
 * resolution. Pure and deterministic — same seed and action sequence
 * produce identical CombatState and event logs.
 */
export { takeAction } from "./actions";
export {
  allyAbilityIds,
  allyArmor,
  allyCombatant,
  allyCombatantId,
  allyStartTile,
  allyStats,
  allyWeapon,
  companionIdOf,
} from "./ally";
export { chooseEnemyAction, runEnemyTurns } from "./ai";
export {
  abilityAreaTiles,
  abilityImpact,
  areaTiles,
} from "./area";
export {
  BASE_FLEE_CHANCE,
  BASE_HIT_CHANCE,
  CRITICAL_DAMAGE_SHARE,
  HEAVY_DAMAGE_SHARE,
  MELEE_RANGE,
  RANGED_RANGE,
  UNARMED_WEAPON,
  abilityDamage,
  abilityHit,
  attackDamage,
  attackHitChance,
  attackStatKey,
  damageBonus,
  effectiveArmor,
  fleeChance,
  hitChance,
  isCriticalBlow,
  isGlancingBlow,
  isHeavyBlow,
  weaponRange,
  weaponReach,
  type AbilityHit,
} from "./damage";
export {
  SURGE_ARM_TURNS,
  SURGE_STUN_TURNS,
  closeSurgeTurn,
  isSurgeArmed,
  openSurgeTurn,
  pendingSurge,
  startingSurge,
  surgeTurnsToArm,
} from "./surge";
export {
  chargeImpact,
  isCharged,
  isUnderThreat,
  pendingCharge,
  pendingCharges,
  threatenedTiles,
  windUpTurns,
} from "./charge";
export {
  SINGLE_TILE,
  bodiesOverlap,
  bodyCovers,
  bodyGap,
  bodyTiles,
  footprintCenter,
  footprintCovers,
  footprintFits,
  footprintGap,
  footprintOf,
  footprintTiles,
  footprintsOverlap,
  isMultiTile,
  tileGap,
  type FootprintBody,
} from "./footprint";
export {
  canStand,
  combatantAt,
  inBounds,
  isBlocked,
  isOccupied,
  manhattan,
  moveSpeed,
} from "./grid";
export {
  abilityOptions,
  attackOptions,
  fleeChanceFor,
  itemOptions,
  manhattanPath,
  reachableTiles,
  type AbilityOption,
  type AbilityTargetOption,
  type AttackOption,
  type ItemOption,
} from "./legal";
export { combatResultFlag, resolveCombat } from "./outcome";
export {
  COMBAT_ACTION_KINDS,
  abilityPreviews,
  actionAvailabilities,
  actionAvailability,
  attackPreview,
  movePreview,
  outcomesFor,
  type AbilityPreview,
  type ActionAvailability,
  type ActionBlockReason,
  type AttackPreview,
  type CombatActionKind,
  type MovePreview,
  type OutcomePreview,
  type OutcomeStatus,
  type PreviewIntent,
} from "./preview";
export {
  TELEGRAPH_REASONS,
  TELEGRAPH_ROLES,
  resolveTelegraphTiles,
  telegraphField,
  telegraphHover,
  telegraphTargetAt,
  telegraphTiles,
  threatTiles,
  type TelegraphHover,
  type TelegraphIntent,
  type TelegraphReason,
  type TelegraphRole,
  type TelegraphTile,
} from "./telegraph";
export { PLAYER_COMBATANT_ID, createCombat } from "./setup";
export {
  activeCombatant,
  allyCombatants,
  areOpposed,
  combatStat,
  getCombatant,
  isAlive,
  initiativeScore,
  isHostile,
  isPlayerControlled,
  livingCrew,
  livingEnemies,
  playerCombatant,
  requireCombatant,
} from "./state";
export {
  CombatError,
  type ActiveBoost,
  type ChargedAction,
  type CombatAction,
  type CombatConsumable,
  type CombatErrorCode,
  type CombatEvent,
  type CombatState,
  type CombatStatus,
  type CombatWeapon,
  type Combatant,
  type CombatantKind,
  type GridPosition,
  type GridSize,
  type StaticSurge,
} from "./types";
