/**
 * Minigames: self-contained puzzles the world can hand a player, each
 * one pure logic with its own overlay in src/ui/. Breach is the first.
 */
export {
  BreachError,
  CHAIN_LENGTH,
  CHAIN_REFUND,
  FRAGMENT_TYPES,
  breachOutcome,
  breachSeed,
  canStep,
  generateLattice,
  headId,
  headNode,
  latticeNode,
  latticeView,
  neighbours,
  nodeId,
  nodeView,
  onPath,
  requireNode,
  routeBreach,
  startBreach,
  stepBreach,
  stepCostOf,
  stepRefusal,
  stepTargets,
  undoBreach,
  visibleKind,
  withdrawBreach,
  type BreachErrorCode,
  type BreachGame,
  type BreachLattice,
  type BreachNode,
  type BreachNodeKind,
  type BreachNodeView,
  type BreachOutcome,
  type BreachProfile,
  type BreachStatus,
  type BreachVision,
  type FragmentType,
  type LatticeSpec,
} from "./breach";
export {
  BREACH_NET_BONUS,
  BREACH_NET_TAG,
  BREACH_TECH_FLOOR,
  BREACH_TRACE_TAG,
  BREACH_TRACE_TECH,
  BREACH_VALUE_TAG,
  CREDITS_PER_CHAIN,
  CREDITS_PER_DATA,
  breachAward,
  breachLockouts,
  breachRescueOffered,
  breachSpent,
  openBreach,
  readRunner,
  settleBreach,
  type BreachAward,
  type BreachSettlement,
  type RunnerRead,
} from "./runner";
