/**
 * Story graph engine: nodes, choices, and typed requirement/effect gating
 * over GameState. Pure functions only — story content lives in
 * src/data/story/.
 */
export { PLAYER_SPEAKER } from "./types";
export type {
  AddItemEffect,
  BackgroundRequirement,
  Choice,
  CompanionComment,
  CompanionLoyaltyEffect,
  CompanionRequirement,
  CreditsEffect,
  Effect,
  EndEffect,
  EnhancementRequirement,
  FlagAtLeastRequirement,
  FlagEqualsRequirement,
  FlagNotEqualsRequirement,
  FlagUnsetRequirement,
  GotoEffect,
  IncrementFlagEffect,
  FlagSetRequirement,
  ItemRequirement,
  LoyaltyRequirement,
  OpenStylistEffect,
  RecruitCompanionEffect,
  RemoveItemEffect,
  Requirement,
  ReputationRequirement,
  SetFlagEffect,
  StartCombatEffect,
  StatRequirement,
  StoryArc,
  StoryNode,
  UnavailablePresentation,
} from "./types";
export { checkRequirement, checkRequirements } from "./requirements";
export {
  BARK_FADE_IN_MS,
  BARK_FADE_OUT_MS,
  BARK_LIFE_MS,
  CUE_PATIENCE_MS,
  GLOBAL_COOLDOWN_MS,
  MAX_LIVE_BARKS,
  NPC_BARK_RANGE,
  NPC_LINGER_MS,
  PEDESTRIAN_BARK_RANGE,
  REPEAT_COOLDOWN_MS,
  SPEAKER_COOLDOWN_MS,
  WOUNDED_BARK_RATIO,
  barkAlphaAt,
  canHear,
  createBarkSchedule,
  cueBark,
  eligibleBarks,
  expireBarks,
  isWounded,
  pickBark,
  silenceBarks,
  stepBarks,
  type BarkCandidate,
  type BarkContext,
  type BarkSchedule,
  type BarkSpeaker,
  type BarkTick,
  type LiveBark,
  type PendingCue,
} from "./barks";
export {
  companionAside,
  companionAsides,
  type CompanionAside,
} from "./companions";
export { applyEffect, applyEffects } from "./effects";
export {
  applyLoyaltyChanges,
  bondSceneReady,
  choiceLoyaltyChanges,
  personalSceneReady,
  reactionChanges,
  reactionTotal,
  readyCompanionScenes,
  readyPersonalScenes,
  witnesses,
  type CompanionSceneKind,
  type LoyaltyChange,
  type ReadyCompanionScene,
} from "./loyalty";
export {
  applyStandingChanges,
  bandCrossings,
  choiceStandingChanges,
  standingChanges,
  type StandingChange,
} from "./standing";
export {
  NarrativeError,
  applyChoice,
  availableChoices,
  getNode,
  requireNode,
  type ChoiceOutcome,
  type NarrativeErrorCode,
  type PresentedChoice,
} from "./engine";
export { validateArc, type ArcIssue, type ArcIssueCode } from "./validate";
export {
  MAX_INTERLUDE_BEATS,
  MIN_INTERLUDE_BEATS,
  composeInterlude,
  interludeReached,
  interludeSeen,
  interludeSeenFlag,
  latestInterlude,
  markInterludeSeen,
  pendingInterlude,
  selectBeats,
  selectStrandBeat,
  type ComposedInterlude,
  type Interlude,
  type InterludeBackdrop,
  type InterludeBeat,
  type InterludeStrand,
  type InterludeVariant,
} from "./interlude";
export {
  EPILOGUE_SECTIONS,
  composeEpilogue,
  sectionRank,
  selectVignettes,
  threadIndex,
  threadVariantIds,
  type EpilogueSection,
  type EpilogueThread,
  type EpilogueVignette,
} from "./epilogue";
