/**
 * Isometric scene: 2:1 diamond-tile renderer, tilemap model, depth sort,
 * pathfinding, picking, and the interactive scene controller.
 */
export {
  TILE_H,
  TILE_W,
  sameTile,
  screenToTile,
  screenToWorld,
  tileDistance,
  worldToScreen,
  type ScreenPoint,
  type TilePoint,
  type WorldPoint,
} from "./coords";
export { compareDrawables, depthOf, sortDrawables, type DrawLayer, type Drawable } from "./depth";
export {
  type IsoFocusHint,
  type IsoFocusHintHandler,
  type IsoInteractionEvent,
  type IsoInteractionHandler,
  type MapInteraction,
} from "./events";
export {
  DEFAULT_OUTLINE_PALETTE,
  INTERACT_RANGE,
  OUTLINE_COLORS,
  focusInteractable,
  interactablesInRange,
  nearestInteractable,
  outlineColor,
  type FocusQuery,
  type FocusReason,
  type FocusedInteractable,
  type OutlinePaletteId,
} from "./affordance";
export { findPath, findPathToAdjacent } from "./path";
export {
  MAX_AMBIENT_PER_MAP,
  ambientLookSeed,
  ambientSpriteId,
  createCrowd,
  crowdEntities,
  inZone,
  resolveZones,
  roamTiles,
  stepCrowd,
  stepPedestrian,
  type AmbientCrowd,
  type AmbientPedestrian,
  type AmbientZoneState,
} from "./ambient";
export {
  CAMERA_MARGIN,
  cameraDistance,
  clampCamera,
  focusCamera,
  initialCamera,
  lerpCamera,
  mapPixelBounds,
  type Camera,
  type PixelBounds,
} from "./camera";
export {
  FOCUS_GLIDE_MS,
  FOCUS_SETTLE_PX,
  IMPACT_FEEL,
  IMPACT_WEIGHTS,
  MAX_PAUSE_MS,
  MAX_SHAKE_PX,
  NO_PAUSES,
  SHAKE_CYCLES,
  advancePauses,
  combinedShakeAt,
  glideCameraAt,
  glideDone,
  hitPauseMs,
  insertPause,
  planCameraGlide,
  resolveCombatFeel,
  sceneTimeAt,
  shakeAmplitudePx,
  shakeDirection,
  shakeFinished,
  shakeOffsetAt,
  type CameraGlide,
  type CombatFeel,
  type CombatFeelSettings,
  type ImpactFeelSpec,
  type ImpactWeight,
  type PauseTimeline,
  type ScenePause,
  type ShakeOffset,
  type ShakeSource,
  type TurnPace,
} from "./cameraFeel";
export {
  DAY_PHASES,
  DEFAULT_DAY_PHASE,
  ENTRY_SPAWN_ID,
  TILE_DEFS,
  buildMapGrid,
  entryFacing,
  inBounds,
  interactableAt,
  isWalkable,
  mapExits,
  neighbors,
  requireSpawn,
  spawnPoint,
  tileAt,
  type Interactable,
  type MapExit,
  type InteractableSpriteId,
  type IsoMap,
  type LegendEntry,
  type PropId,
  type PropPlacement,
  type AmbientSpec,
  type AmbientZone,
  type DayPhaseId,
  type DronePath,
  type SetPieceSpec,
  type TrainTrack,
  type VentBurstSpec,
  type SpawnPoint,
  type TileDef,
  type TileId,
  type WeatherId,
} from "./tilemap";
export { glowIntensityScale, resolveDayPhase } from "./dayPhase";
export {
  FACING_STEP,
  MINIMAP_CELL_MAX,
  MINIMAP_CELL_MIN,
  MINIMAP_COLORS,
  MINIMAP_MAX_PX,
  minimapCell,
  minimapCells,
  minimapLayout,
  minimapPipKind,
  minimapPips,
  minimapViewport,
  pipSize,
  sameMinimapView,
  tickLength,
  tileCenter,
  tileTopLeft,
  type MinimapCell,
  type MinimapLayout,
  type MinimapPip,
  type MinimapPipKind,
  type MinimapPlayer,
  type MinimapRect,
  type MinimapView,
} from "./minimap";
export {
  ARENA_STREAK_DENSITY,
  PUDDLE_DENSITY,
  RAIN_LAYERS,
  activeSplashes,
  puddleAt,
  puddleTiles,
  rainStreaks,
  resolveWeather,
  shimmerFactor,
  splashFrameAt,
  tileHoldsWater,
  tileKey,
  wetTiles,
  type RainLayer,
  type RainStreak,
  type Splash,
  type WeatherView,
} from "./weather";
export {
  DRONE_BOB_PERIOD_MS,
  DRONE_BOB_PX,
  STEAM_FRAME_MS,
  STEAM_MOUTH_OFFSET_Y,
  TRAIN_CAR_SPAN,
  VENT_RAIN_FACTOR,
  collectSetPieces,
  droneBobPx,
  droneDraws,
  dronePathLength,
  droneStateAt,
  setPieceGlows,
  trainDraws,
  trainRunAt,
  ventBurstFrameAt,
  ventDraws,
  type DroneState,
  type SetPieceDraw,
  type SetPieceOptions,
  type TrainRun,
} from "./setpiece";
export { createIsoScene, type IsoScene, type IsoSceneOptions } from "./scene";
export {
  type FocusView,
  type OpeningView,
  type RenderView,
  type SceneEntity,
} from "./render";
export {
  DOOR_TIMING,
  TRANSITION_CUT,
  TRANSITION_TIMING,
  coverAlpha,
  destinationShown,
  doorCycleMs,
  doorFrameIndex,
  doorOpen01,
  doorTiming,
  transitionDurationMs,
  transitionPhaseAt,
  transitionSwapMs,
  transitionTiming,
  type DoorTiming,
  type TransitionPhase,
  type TransitionTiming,
} from "./transition";
export {
  createCombatScene,
  type AttackFxOptions,
  type CombatHighlights,
  type CombatPopupRequest,
  type CombatScene,
  type CombatSceneEntity,
  type CombatSceneOptions,
  type HitFxOptions,
  type TelegraphTileView,
} from "./combatScene";
export {
  DEFAULT_TELEGRAPH_PALETTE,
  TELEGRAPH_PAINT_ORDER,
  TELEGRAPH_PALETTES,
  TELEGRAPH_PALETTE_IDS,
  TELEGRAPH_PATH_LINE,
  TELEGRAPH_TINT_IDS,
  telegraphStyle,
  type TelegraphPaletteId,
  type TelegraphStyle,
  type TelegraphTintId,
} from "./telegraphPalette";
export {
  POPUP_BADGE_IDS,
  POPUP_KINDS,
  POPUP_LIFT_PX,
  POPUP_MS,
  POPUP_RISE_PX,
  POPUP_STACK_PX,
  POPUP_STYLES,
  STATUS_POPUP_LABELS,
  nextPopupSlot,
  popupMotionAt,
  popupSlotOffsetPx,
  statusPopupKind,
  statusPopupLabel,
  type PopupBadgeId,
  type PopupKind,
  type PopupMotion,
  type PopupSlotView,
  type PopupStyle,
  type StatusPopupPhase,
} from "./popup";
export {
  ABILITY_FX,
  ABILITY_FX_IDS,
  AURA_CAST_MS,
  BEAM_AMPLITUDE_PX,
  BEAM_MAX_SEGMENTS,
  abilityCastMs,
  abilityFxFrameAt,
  abilityFxSequence,
  beamPoints,
  beamSegmentCount,
  castsWithWeapon,
  planAbilityCast,
  type AbilityCastPlan,
  type AbilityFxForm,
  type AbilityFxId,
  type AbilityFxOptions,
  type AbilityFxPlay,
  type AbilityFxReaction,
  type AbilityFxSequence,
  type AbilityFxSpec,
  type AbilityFxTarget,
  type AbilityFxWindow,
} from "./abilityFx";
export {
  BOOST_FAMILY,
  STATUS_FAMILY_IDS,
  STATUS_MARKERS,
  STATUS_MARKER_SPACING_PX,
  boostStatusFamily,
  statusFamilies,
  statusMarkerFrame,
  statusMarkerOffsets,
  type StatusFamilyId,
  type StatusMarkerSpec,
  type StatusView,
} from "./status";
export {
  ATTACK_FX_STYLE,
  EFFECT_SPRITE_IDS,
  EFFECT_TIMING,
  MISS_OVERSHOOT_TILES,
  REDUCED_IMPACT_MS,
  TRACER_DIRECTIONS,
  TRACER_MAX_MS,
  TRACER_MIN_MS,
  TRACER_SPEED_PX_PER_MS,
  effectFrameAt,
  effectKind,
  effectSpriteId,
  impactKind,
  impactSequence,
  launchKind,
  overshootPoint,
  swipeSpriteId,
  tracerDirection,
  tracerPointAt,
  tracerProgress,
  tracerSpriteId,
  tracerTravelMs,
  type AttackFxStyle,
  type EffectKind,
  type EffectSpriteId,
  type EffectWindow,
  type ImpactOptions,
  type ImpactSequence,
  type TracerDirection,
} from "./impact";
export {
  DEATH_REACTION_KINDS,
  HIT_REACTION_KINDS,
  REACTION_KINDS,
  REACTION_STAGGER_MS,
  REACTION_TIMING,
  activeReaction,
  isDeathReaction,
  latestBeatFor,
  pruneReactions,
  reactionDurationMs,
  reactionFrameAt,
  reactionFrameCount,
  reactionPoseAt,
  reactionSequence,
  scheduleReaction,
  type DeathReactionKind,
  type HitReactionKind,
  type ReactionKind,
  type ReactionPose,
  type ReactionRequest,
  type ReactionSequence,
  type ReactionVariant,
  type ScheduledReaction,
} from "./reaction";
export {
  type EntityPose,
  type EntitySpriteId,
  type SetPieceSpriteId,
  type Sprite,
  type SpriteProvider,
} from "./sprites";
export {
  createPixelArtSprites,
  type PixelArtSpriteOptions,
  type PixelArtSprites,
} from "./art/provider";
export {
  attackClassFor,
  composedCharacterKey,
  type ComposedCharacter,
  type ComposedLayer,
} from "./art/layers";
export {
  ENTITY_ART_KINDS,
  characterArt,
  droneArt,
  entityAttackClass,
  entityAttackVariants,
  entityFrame,
  entityFrameKey,
  entityGrid,
  entityMuzzlePoint,
  mechArt,
  type CharacterEntityArt,
  type DroneEntityArt,
  type EntityArt,
  type EntityArtKind,
  type EntityFrame,
  type MechEntityArt,
} from "./art/entity";
export {
  MECH_ART,
  MECH_ART_IDS,
  MECH_FRAME,
  MECH_SET_IDS,
  MECH_VIEW_IDS,
  mechAttackClass,
  mechFrameCount,
  mechGrid,
  mechMuzzlePoint,
  mechViewForFacing,
  type MechArt,
  type MechArtId,
  type MechSetId,
  type MechViewId,
} from "./art/mech";
export {
  DRONE_ART,
  DRONE_ART_IDS,
  DRONE_SET_IDS,
  droneFrameCount,
  type DroneArt,
  type DroneArtId,
  type DroneSetId,
} from "./art/drone";
export {
  ATTACK_CLASS_IDS,
  ATTACK_TIMING,
  attackDurationMs,
  attackFrameAt,
  attackFrameCount,
  attackImpactMs,
  attackSequence,
  selectMotionFrame,
  type AttackClassId,
  type AttackFrameWindow,
  type AttackSequence,
  type AttackTiming,
  type MotionQuery,
} from "./attack";
export { type SpriteCacheStats } from "./art/spriteCache";
export {
  facingFromDelta,
  frameAt,
  pulse01,
  smoothStep01,
  variantIndex,
  type Facing,
  type LoopState,
  type MotionState,
} from "./animation";
